# Generated by Django 5.1.7 on 2025-03-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_category_marketplaceitem_userpreference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('waste_generated_tons', models.FloatField()),
            ],
            options={
                'ordering': ['timestamp'],
                'unique_together': {('timestamp', 'location')},
            },
        ),
        migrations.CreateModel(
            name='WastePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('predicted_waste_tons', models.FloatField()),
                ('lower_bound', models.FloatField()),
                ('upper_bound', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
                'unique_together': {('timestamp', 'location')},
            },
        ),
    ]
